rename	xl110x_hal_flash.c	sip_mcu_hal_flash.c
rename	xl110x_hal_gpio.c	sip_mcu_hal_gpio.c
rename	xl110x_hal_i2c.c	sip_mcu_hal_i2c.c
rename	xl110x_hal_irda.c	sip_mcu_hal_irda.c
rename	xl110x_hal_iwdg.c	sip_mcu_hal_iwdg.c
rename	xl110x_hal_led.c	sip_mcu_hal_led.c
rename	xl110x_hal_lptim.c	sip_mcu_hal_lptim.c
rename	xl110x_hal_pwr.c	sip_mcu_hal_pwr.c
rename	xl110x_hal_rcc.c	sip_mcu_hal_rcc.c
rename	xl110x_hal_rcc_ex.c	sip_mcu_hal_rcc_ex.c
rename	xl110x_hal_rtc.c	sip_mcu_hal_rtc.c
rename	xl110x_hal_rtc_ex.c	sip_mcu_hal_rtc_ex.c
rename	xl110x_hal_spi.c	sip_mcu_hal_spi.c
rename	xl110x_hal_tim.c	sip_mcu_hal_tim.c
rename	xl110x_hal_tim_ex.c	sip_mcu_hal_tim_ex.c
rename	xl110x_hal_uart.c	sip_mcu_hal_uart.c
rename	xl110x_hal_usart.c	sip_mcu_hal_usart.c
rename	xl110x_hal_wwdg.c	sip_mcu_hal_wwdg.c
rename	xl110x_hal.c	sip_mcu_hal.c
rename	xl110x_hal_adc.c	sip_mcu_hal_adc.c
rename	xl110x_hal_adc_ex.c	sip_mcu_hal_adc_ex.c
rename	xl110x_hal_comp.c	sip_mcu_hal_comp.c
rename	xl110x_hal_cortex.c	sip_mcu_hal_cortex.c
rename	xl110x_hal_crc.c	sip_mcu_hal_crc.c
rename	xl110x_hal_dma.c	sip_mcu_hal_dma.c
rename	xl110x_hal_exti.c	sip_mcu_hal_exti.c
		
rename	xl110x_hal_flash_ex.h	sip_mcu_hal_flash_ex.h
rename	xl110x_hal_gpio.h	sip_mcu_hal_gpio.h
rename	xl110x_hal_gpio_ex.h	sip_mcu_hal_gpio_ex.h
rename	xl110x_hal_i2c.h	sip_mcu_hal_i2c.h
rename	xl110x_hal_irda.h	sip_mcu_hal_irda.h
rename	xl110x_hal_iwdg.h	sip_mcu_hal_iwdg.h
rename	xl110x_hal_led.h	sip_mcu_hal_led.h
rename	xl110x_hal_lptim.h	sip_mcu_hal_lptim.h
rename	xl110x_hal_pwr.h	sip_mcu_hal_pwr.h
rename	xl110x_hal_rcc.h	sip_mcu_hal_rcc.h
rename	xl110x_hal_rcc_ex.h	sip_mcu_hal_rcc_ex.h
rename	xl110x_hal_rtc.h	sip_mcu_hal_rtc.h
rename	xl110x_hal_rtc_ex.h	sip_mcu_hal_rtc_ex.h
rename	xl110x_hal_spi.h	sip_mcu_hal_spi.h
rename	xl110x_hal_tim.h	sip_mcu_hal_tim.h
rename	xl110x_hal_tim_ex.h	sip_mcu_hal_tim_ex.h
rename	xl110x_hal_uart.h	sip_mcu_hal_uart.h
rename	xl110x_hal_usart.h	sip_mcu_hal_usart.h
rename	xl110x_hal_wwdg.h	sip_mcu_hal_wwdg.h
rename	py32f0xx_ll_exti.h	py32f0xx_ll_exti.h
rename	xl110x_hal.h	sip_mcu_hal.h
rename	xl110x_hal_adc.h	sip_mcu_hal_adc.h
rename	xl110x_hal_adc_ex.h	sip_mcu_hal_adc_ex.h
rename	xl110x_hal_comp.h	sip_mcu_hal_comp.h
rename	xl110x_hal_cortex.h	sip_mcu_hal_cortex.h
rename	xl110x_hal_crc.h	sip_mcu_hal_crc.h
rename	xl110x_hal_def.h	sip_mcu_hal_def.h
rename	xl110x_hal_dma.h	sip_mcu_hal_dma.h
rename	xl110x_hal_dma_ex.h	sip_mcu_hal_dma_ex.h
rename	xl110x_hal_exti.h	sip_mcu_hal_exti.h
rename	xl110x_hal_flash.h	sip_mcu_hal_flash.h
